### PR TITLE
Fix bug in Route ToString method when any of Hosts, Paths, Methods or…

### LINKED ISSUE #20: Route ToString method breaks when Hosts, Paths, Methods or Protocols are null
The `ToString()` method override for `Route` fails when any of the following properties are `null`:
* Hosts
* Paths
* Methods
* Protocols

### PR DESCRIPTION
**Pull request by shaynevanasperen**
… Protocols are null. Also improve validation messages for when Hosts values are invalid. Fixes #20

### CODE REVIEW

**Review by Gadam8 — APPROVED** [review]

File: src/Kongverge/DTOs/KongRoute.cs [hunk 1]
```diff
@@ -87,19 +98,27 @@ public virtual async Task Validate(IReadOnlyCollection<string> availablePlugins,
...
-            if (Hosts == null || Hosts.Any(x => string.IsNullOrWhiteSpace(x) || x.StartsWith("*.") && x.EndsWith(".*") || Uri.CheckHostName(RemoveWildcards(x)) == UriHostNameType.Unknown))
+            if (Hosts?.Any(string.IsNullOrWhiteSpace) == true)
+            {
+                errorMessages.Add("Route Hosts is invalid (cannot contain null or empty values).");
+            }
+            if (Hosts?.Any(x => !string.IsNullOrWhiteSpace(x) && x.StartsWith("*.") && x.EndsWith(".*")) == true)
+            {
+                errorMessages.Add("Route Hosts is invalid (values cannot begin and end with a wildcard, only one wildcard at the start or end is allowed).");
+            }
+            if (Hosts?.Any(x => !string.IsNullOrWhiteSpace(x) && Uri.CheckHostName(RemoveWildcards(x)) == UriHostNameType.Unknown) == true)
```
Comment (tsbala) [inline src/Kongverge/DTOs/KongRoute.cs:109]: nit picking, needs a blank line

Comment (shaynevanasperen) [reply src/Kongverge/DTOs/KongRoute.cs:109]: This was intentional, as this batch of if-statements are all checking the same property.
